services:
  kafka:
     image: bitnami/kafka:3.5
     container_name: kafka
     ports:
      - "9092:9092"
     environment: 
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_CLUSTER_ID: 'kraft-cluster-12345'

  servicio-usuarios:
    build: ./microservice-1
    ports:
      - "5000:5000"
    depends_on:
      - kafka
  
  servicio-notificaciones: 
    build: ./microservice2
    ports:
      - "5001:5001"
    depends_on:
      - kafka